language:
    objective-c
osx_image:
    xcode8
xcode_project:
    PausableTimer.xcodeproj
xcode_scheme:
    PausableTimer
script:
  - carthage update --platform iOS
  - xcodebuild -project PausableTimer.xcodeproj -scheme PausableTimer 'platform=iOS Simulator,name=iPhone 7 Plus,OS=10.0' clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty

