language:
    objective-c
osx_image:
    xcode9
xcode_project:
    PausableTimer.xcodeproj
xcode_scheme:
    PausableTimer
script:
  - carthage update --platform iOS
  - bundle install --path vendor/bundle
  - bundle exec fastlane scan --scheme 'PausableTimer'
