language:
    objective-c
osx_image:
    xcode7.3
xcode_project:
    PausableTimer.xcodeproj
xcode_scheme:
    PausableTimer
script:
  - carthage update --platform iOS
  - xcodebuild test -project PausableTimer.xcodeproj -scheme PausableTimer | xcpretty -c

